export const portableMeals = [
  // Breakfast
  {
    id: "huevos_pita_integral",
    name: "Huevos duros con pan pita integral",
    foods: ["huevo", "pan_pita_integral"],
    mealType: "breakfast",
    requiresRefrigeration: false,
    portable: true,
    maxHoursWithoutFridge: 12,
    difficulty: "easy",
    satietyLevel: "high",
  },
  {
    id: "yogurt_avena_desayuno",
    name: "Yogurt con avena",
    foods: ["yogurt", "avena"],
    mealType: "breakfast",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 2,
    difficulty: "easy",
    satietyLevel: "medium",
  },
  {
    id: "pan_palta_desayuno",
    name: "Pan con palta",
    foods: ["pan_integral", "palta"],
    mealType: "breakfast",
    requiresRefrigeration: false,
    portable: true,
    maxHoursWithoutFridge: 6,
    difficulty: "easy",
    satietyLevel: "medium",
  },
  {
    id: "sandwich_pavo_tomate",
    name: "Sandwich integral de pavo y tomate",
    foods: ["pan_integral", "jamon_de_pavo", "tomate"],
    mealType: "breakfast",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 4,
    difficulty: "easy",
    satietyLevel: "high",
  },
  {
    id: "overnight_oats",
    name: "Overnight oats con fruta",
    foods: ["avena", "leche", "platano"],
    mealType: "breakfast",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 2,
    difficulty: "easy",
    satietyLevel: "high",
  },
  {
    id: "quesillo_pita",
    name: "Quesillo con pan pita integral",
    foods: ["quesillo", "pan_pita_integral"],
    mealType: "breakfast",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 3,
    difficulty: "easy",
    satietyLevel: "high",
  },
  {
    id: "huevo_platano",
    name: "Huevos duros con plátano",
    foods: ["huevo", "platano"],
    mealType: "breakfast",
    requiresRefrigeration: false,
    portable: true,
    maxHoursWithoutFridge: 10,
    difficulty: "easy",
    satietyLevel: "high",
  },

  // Snacks
  {
    id: "manzana_nueces",
    name: "Manzana con nueces",
    foods: ["manzana", "nuez"],
    mealType: "snack",
    requiresRefrigeration: false,
    portable: true,
    maxHoursWithoutFridge: 24,
    difficulty: "easy",
    satietyLevel: "medium",
  },
  {
    id: "huevos_duros_snack",
    name: "Huevos duros",
    foods: ["huevo"],
    mealType: "snack",
    requiresRefrigeration: false,
    portable: true,
    maxHoursWithoutFridge: 12,
    difficulty: "easy",
    satietyLevel: "high",
  },
  {
    id: "yogurt_griego_frutilla",
    name: "Yogurt griego con frutilla",
    foods: ["yogurt_griego", "frutilla"],
    mealType: "snack",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 2,
    difficulty: "easy",
    satietyLevel: "medium",
  },
  {
    id: "almendras_platano",
    name: "Almendras con plátano",
    foods: ["almendra", "platano"],
    mealType: "snack",
    requiresRefrigeration: false,
    portable: true,
    maxHoursWithoutFridge: 24,
    difficulty: "easy",
    satietyLevel: "high",
  },
  {
    id: "queso_cottage_manzana",
    name: "Queso cottage con manzana",
    foods: ["queso_cottage", "manzana"],
    mealType: "snack",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 2,
    difficulty: "easy",
    satietyLevel: "medium",
  },
  {
    id: "barrita_mani",
    name: "Barrita de cereal con maní",
    foods: ["barrita_de_cereal", "mani"],
    mealType: "snack",
    requiresRefrigeration: false,
    portable: true,
    maxHoursWithoutFridge: 24,
    difficulty: "easy",
    satietyLevel: "medium",
  },
  {
    id: "atun_crackers_snack",
    name: "Atún en lata con galleta de soda",
    foods: ["atun_en_lata", "galleta_de_soda"],
    mealType: "snack",
    requiresRefrigeration: false,
    portable: true,
    maxHoursWithoutFridge: 24,
    difficulty: "easy",
    satietyLevel: "high",
  },

  // Portable dinners
  {
    id: "atun_crackers_dinner",
    name: "Atún con galletas integrales",
    foods: ["atun_en_lata", "galleta_de_soda"],
    mealType: "dinner",
    requiresRefrigeration: false,
    portable: true,
    maxHoursWithoutFridge: 24,
    difficulty: "easy",
    satietyLevel: "high",
  },
  {
    id: "pan_queso_cena",
    name: "Pan con queso",
    foods: ["pan_integral", "queso"],
    mealType: "dinner",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 3,
    difficulty: "easy",
    satietyLevel: "medium",
  },
  {
    id: "sandwich_pollo",
    name: "Sandwich de pollo a la plancha",
    foods: ["pan_integral", "pollo_a_la_plancha", "tomate"],
    mealType: "dinner",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 4,
    difficulty: "medium",
    satietyLevel: "high",
  },
  {
    id: "wrap_pavo_palta",
    name: "Wrap de pavo con palta",
    foods: ["tortilla_de_trigo", "jamon_de_pavo", "palta"],
    mealType: "dinner",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 4,
    difficulty: "medium",
    satietyLevel: "high",
  },
  {
    id: "ensalada_lentejas",
    name: "Ensalada fría de lentejas",
    foods: ["lentejas_cocidas", "tomate", "pepino"],
    mealType: "dinner",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 3,
    difficulty: "medium",
    satietyLevel: "high",
  },
  {
    id: "hummus_pita",
    name: "Garbanzos triturados con pan pita",
    foods: ["garbanzos_cocidos", "pan_pita_integral"],
    mealType: "dinner",
    requiresRefrigeration: false,
    portable: true,
    maxHoursWithoutFridge: 8,
    difficulty: "easy",
    satietyLevel: "medium",
  },
  {
    id: "quesillo_tomate_pan",
    name: "Quesillo, tomate y pan integral",
    foods: ["quesillo", "tomate", "pan_integral"],
    mealType: "dinner",
    requiresRefrigeration: true,
    portable: true,
    maxHoursWithoutFridge: 3,
    difficulty: "easy",
    satietyLevel: "high",
  },
];

export function getPortableMeals() {
  return portableMeals;
}

export function getPortableMealsByType(type) {
  const mealType = String(type || "").trim().toLowerCase();
  return portableMeals.filter((meal) => String(meal?.mealType || "").toLowerCase() === mealType);
}

export function getNoFridgeMeals() {
  return portableMeals.filter((meal) => meal?.requiresRefrigeration === false);
}

export function filterMealsBySatiety(level) {
  const satietyLevel = String(level || "").trim().toLowerCase();
  return portableMeals.filter(
    (meal) => String(meal?.satietyLevel || "").toLowerCase() === satietyLevel
  );
}
